### ISSUE TITLE
Issues in submitted `1.0.1-a.1` package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/linenoise#1]
- [x] Repository in the [build2-packaging organization][build2-packaging] if third-party package.
- [x] Repository/project/package names consistent with upstream, [Debian][debian-pkgs] ([see also][name-packages]).
- [x] Use git submodule and symlinks for upstream, submodule at release commit.
- [x] [Do not change upstream layout (without good reason)][upstream-layout].

- [x] Successful builds on [queue.cppget.org][queue].
- [x] Package archive sizes are not excessive and don't contain unnecessary files.

- [x] `manifest`: `name`/`project`/[`version`][manifest-version] values make sense.
- [x] `manifest`: [`summary`][manifest-summary] value follows guidelines.
- [x] `manifest`: [`license`][manifest-license] value is SPDX, matches upstream license(s).

- [x] `build/bootstrap.build`: makes sense (project name, modules)
- [x] `build/root.build`:      makes sense (`cxx.std=latest`)
- [x] `build/export.build`:    makes sense

- [x] root directory/`buildfile`: include upstream `LICENSE` file (or equivalent).
- [x] root directory/`buildfile`: [don't build main targets][root-main-targets].

- [x] source directory/`buildfile`: [bdep-new generated][use-bdep-new]
- [x] source directory/`buildfile`: [don't use or export undesirable options][compile-options]
- [x] source directory/`buildfile`: [library is not header-only if upstream supports compiled][header-only]
- [x] source directory/`buildfile`: headers installed into library subdirectory or include library name

- [x] above checks applied to tests/examples/etc subprojects/packages

Minor note/wish: In a "smoke test" (like the one you provide in `tests/basics`) it is generally recommended that you not only include the header, but also try to call some preferably non-inline function to make sure the built library can actually be linked.

Migrated to testing, thanks!

[build2-packaging]: https://github.com/build2-packaging/
[upstream-layout]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-change-upstream
[debian-pkgs]: packages.debian.org/
[name-packages]: https://github.com/build2/HOWTO/blob/master/entries/name-packages-in-project.md

[queue]: https://queue.cppget.org

[manifest-version]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-forget-update-manifest-version
[manifest-license]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-forget-update-manifest-license
[manifest-summary]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-forget-update-manifest-summary

[root-main-targets]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-main-target-root-buildfile

[use-bdep-new]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-from-scratch
[compile-options]: https://github.com/build2/HOWTO/blob/master/entries/compile-options-in-buildfile.md
[header-only]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-header-only

**Comment by lyrahgames** [comment]
> Minor note/wish: In a "smoke test" (like the one you provide in `tests/basics`) it is generally recommended that you not only include the header, but also try to call some preferably non-inline function to make sure the built library can actually be linked.

Yeah, you are right. It is very difficult to test `readline`-like/REPL libraries.
So, I only provided the example for compilation without tests.
In the above commit, I have improved the smoke test and added some basic I/O testing.
[The current CI run](https://ci.stage.build2.org/@da3c06ef-ab05-4e0a-a3e4-a305f1bc36a5) is successful. I will publish the next revision then.

> Migrated to testing, thanks!

Thank you. You're welcome!
